nfrasser/linkifyjs

- CHANGELOG.md
- src/linkify-element.js
- src/linkify-string.js
- src/linkify/utils/options.js
* **[Breaks previous beta]** Options that take only the link type now take the `href` as well ( #69 )
* Updated linkify-element implementation that is faster and less destructive - No longer rebuilds entire DOM for each element linkify is called on.
Fixes #62 
Fixes #69
> 2.0.0-beta.3 - Updated options and faster linkify-element implementation

- src/linkify-element.js
An array of children is getting built but is never used. It should be removed to save some memory; especially since this is a recursive function.
> Remove unused `children` var

- src/linkify/core/scanner.js
- test/spec/linkify/core/parser-test.js
- test/spec/linkify/core/scanner-test.js
The `toLowerCase` method appears to be modifying the string content in certain non-English text, including Turkish. This fix lowercases *only* A-Z characters, which is okay because lowercasing is really only required to detect domain names and TLDs.
Fixes #87
> Workaround for Chrome `toLowerCase` issue

- src/linkify/core/parser.js
- src/linkify/core/scanner.js
- src/linkify/core/tokens.js
- test/spec/linkify/core/parser-test.js
- test/spec/linkify/core/scanner-test.js
Fixes #80
Fixes #81
Fixes #89
Partially addresses #90 
Implementation for *mostly* correct parsing of URLs that contain brackets, including `({[]})`
* Links wrapped in parens should be parsed correctly
* Links containing a parenthesized expression  should be parsed correctly
* e.g, `/\([^\)]*\)/`
* Links with multiple levels of bracket nesting may or may not be parsed correctly. This plugin will probably never be sophisticated enough to match arbitrary levels of bracket nesting.
> Mostly correct parsing for links containing or wrapped in brackets

- _config.yml
- _layouts/doc.html
- docs/index.md
- docs/linkify-html.md
- docs/linkify-string.md
- index.html
> Docs for new linkify-html interface

- README.md
`require('linkifyjs/plugins/hashtag')(linkify);` is correct; there is no `/plugin/` path per the most recent npm install (2.0.0-beta.8)
> Correct require path for hashtag plugin

- src/linkify/core/parser.js
- test/spec/linkify/core/parser-test.js
This will allow parsing arbitrarily TLDs that begin with a protocol.
* Fixes #19
* Fixes #99
* Fixes #104 
* Fixes #113
> Anything that begins with a protocol is recognized as a string

- src/linkify/core/parser.js
- src/linkify/core/scanner.js
- src/linkify/core/state.js
Instead of
```js
S_TLD.on(TT_COLON, S_TLD_COLON);
S_TLD.on(TT_SLASH, S_URL);
```
Can now write
```js
S_TLD
.on(TT_COLON, S_TLD_COLON)
.on(TT_SLASH, S_URL);
```
> Make state transition definitions chainable

- src/linkify/core/parser.js
- src/linkify/core/scanner.js
- src/linkify/core/state.js
- test/spec/linkify-html-test.js
- test/spec/linkify-string-test.js
- test/spec/linkify/core/parser-test.js
Should help with trailing special character issues
Fixes #108
Fixes #143
Partially addresses #100
> Correct trailing symbol parsing

- README.md
- src/linkify-element.js
- src/linkify-html.js
- src/linkify-jquery.js
- src/linkify-react.js
- src/linkify-string.js
- src/linkify.js
- src/linkify/utils/options.js
- tasks/uglify.js
- test/qunit/main.js
- test/spec/html/extra.html
- test/spec/html/options.js
- test/spec/linkify-html-test.js
- test/spec/linkify-react-test.js
- test/spec/linkify-string-test.js
- test/spec/linkify-test.js
- test/spec/linkify/utils/options-test.js
* Added ability to override default options via `linkify.options.defaults`
* Options that take functions with value and type arguments can now be specified as objects, where each key is the target type. For example:
```js
'github.com is #rad, please email nick@example.com'.linkify({
formatHref: {
email: (mailto) => `${mailto}?subject=Hello`,
hashtag: (hashtag) => `https://twitter.com/hashtag/${hashtag.substr(1)}`
}
});
```
* Allow disabling linkClass (by using default options) - Fixes #144
* Deprecated `linkClass` option. Use `className` instead
* Deprecated `linkAttributes` option. Use `attributes` instead.
* The `linkified` default class name for links will no longer be provided in a future release
* Fully removed deprecated `newLine` option
> Revamped options utility

- src/linkify/core/scanner.js
- test/spec/linkify/core/parser-test.js
- test/spec/linkify/core/scanner-test.js
> Single quotes should be treated as punctuation

- gulpfile.js
Changed `window` to `self` to be able to use in web workers as well.
> web workers support

- src/linkify/utils/options.js
- test/spec/linkify/utils/options-test.js
Type coercion means we cannot override options with null values (or any other falsy values for that matter). This adds undefined checks for target and className (which suited my requirements) and tests to cover these cases.
What do you think? Correct approach? Would other option values benefit from null values?
> Allow null overrides in options for target and className

- test/spec/linkify-html-test.js
Setting `target: null` or `target: { url: null }` doesn't have any effect on the output as [documented](http://soapbox.github.io/linkifyjs/docs/options.html#target). In both cases, URL target is always `_blank`. I'm attaching a failing test.
> [Bug] Setting null target doesn't have any effect

- src/linkify-string.js
- test/spec/linkify-string-test.js
Where possible (other than IE 8), use `Object.defineProperty` to extend the `String` prototype so that the `linkify` function is not enumerable on `String` instances.
This causes iteration over a string to behave correctly:
```
for (i in "test") { console.log(i); }
>> 0
>> 1
>> 2
>> 3
```
By only appending the property to the prototype (`String.prototype.linkify = ...`), you get:
```
for (i in "test") { console.log(i); }
>> 0
>> 1
>> 2
>> 3
>> linkify
```
> use Object.defineProperty to extend String prototype

- src/linkify/plugins/mention.js
- test/spec/linkify/plugins/mention-test.js
This PR adds support for mentions in the format of `@user@domain.com` This is a common pattern if mentions are used in federated protocols across multiple servers, like with ActivityPub.
> mentions: Allow mentions to contain an @-sign

- packages/linkify-element/src/linkify-element.js
- packages/linkify-jquery/src/linkify-jquery.js
- packages/linkify-react/src/linkify-react.js
- packages/linkifyjs/src/core/options.js
- packages/linkifyjs/src/core/parser.js
- packages/linkifyjs/src/core/tokens/multi.js
- packages/linkifyjs/src/linkify-html.js
- packages/linkifyjs/src/linkify-string.js
- packages/linkifyjs/src/linkify.js
- test/index.js
- test/qunit/main.js
- test/spec/core/options.test.js
- test/spec/core/tokens/multi.test.js
- test/spec/linkify-react.test.js
- test/spec/linkify-string.test.js
This will allow for more cohesive formatting in Linkify's core methods, simpler interface implementations and consistent options across interfaces.
***
Fixes #357
Fixes #349
> Unified Token Formatting and Rendering

- docs/xss.md
e.g. https://linkify.js.org/docs/element.html -> https://linkify.js.org/docs/linkify-element.html
> Correct links on XSS page

- packages/linkifyjs/src/parser.js
- test/spec/linkifyjs/parser.test.js
This patch fixes the parser so that it can capture an email address whose local part matches a scheme string, e.g. 'http' or 'mailto'.
Fixes https://github.com/Hypercontext/linkifyjs/issues/414
> Capture email address with its local part being scheme string

- packages/linkify-react/src/linkify-react.js
Just removed duplicate `tagName?` param.
> FIx jsdoc in linkify-react

- packages/linkifyjs/src/parser.js
- packages/linkifyjs/src/scanner.js
- packages/linkifyjs/src/text.js
- test/spec/linkifyjs/parser.test.js
> Add support for fullwidth parentheses

- packages/linkify-html/package.json
- packages/linkify-html/src/linkify-html.js
- test/spec/linkify-html.test.js
> linkify-html: don't convert & -> &amp;

- .github/workflows/ci.yml
- packages/linkifyjs/src/parser.js
- packages/linkifyjs/src/scanner.js
- packages/linkifyjs/src/text.js
- test/run.sh
- test/spec/linkifyjs/parser.test.js
No change in behaviour but a bit cleaner. See also #460, #461
> Bracket parsing refactor and support for 「」『』＜＞ brackets

- packages/linkify-plugin-hashtag/src/hashtag.js
- packages/linkifyjs/src/scanner.js
- packages/linkifyjs/src/text.js
- test/spec/linkify-plugin-hashtag.test.js
- test/spec/linkifyjs/scanner.test.js
Nice to meet you, Thank you for the great OSS you are providing!
I love to using this OSS! 
There is one problem in hashtag plugin with Japanese that I would like to fix, and I am sending this pull request. 
- linkifyjs hashtag plugin cannot parse full width middle dot `・` correctly
- Full width middle dot `・` is a very important symbol in Japanese
- That is used in many cases in Japanese
- Name of person
- Title of the work
- Name of a sports team
- Name of brand
- X (formerly Twitter) supports full width middle dot in hashtags
- `#アラン・チューリング`
- Alan Mathison Turing
- `#スター・ウォーズ`
- STAR WARS
- `#レアル・マドリード`
- Real Madrid CF
- `#コカ・コーラ`
- coca cola
- I've added `FULLWIDTHMIDDLEDOT` to
- `packages/linkifyjs/src/text.js`
- `packages/linkifyjs/src/scanner.js`
- I've updated …
> Fix hashtag plugin: add support for full width middle dot `・`

- packages/linkifyjs/src/scanner.mjs
- test/spec/linkifyjs/parser.test.mjs
> Treat object replacement character as whitespace

- packages/linkifyjs/src/parser.mjs
- test/spec/linkifyjs/parser.test.mjs
Fixes #488 
Single quotes should end URL if encountered.
> Don't allow apostrophe in URLs

- packages/linkifyjs/src/scanner.mjs
- test/spec/linkify-plugin-hashtag.test.mjs
- test/spec/linkifyjs/scanner.test.mjs
So that hashtags preceded by emojis work
Fixes #473
> Correctly interpret emoji followed by pound

- packages/linkifyjs/src/parser.mjs
- test/spec/linkifyjs/parser.test.mjs
> Support for domain names with two hyphens

- packages/linkifyjs/src/parser.mjs
- test/spec/linkifyjs.test.mjs
Fixes #410
Specifically any optionalSlashSlash scheme followed by a question mark, e.g., `magnet:?data...`
Requires registering magnet:
```js
linkify.registerCustomProtocol('magnet', true)
```
> Allow parsing magnet links

- packages/linkifyjs/src/parser.mjs
- test/spec/linkifyjs/parser.test.mjs
Hi,  I didn't know that apostrophe was a valid character in a URL up until a person I know told me about it.  
Here's the reference: https://stackoverflow.com/questions/7109143/what-characters-are-valid-in-a-url/7109208#7109208  
I'm sorry.
> Fix: allow apostrophe in URL
