package.json

v2.0.0-beta.6

---

package.json
src/linkify-html.js
test/spec/linkify-html-test.js

* Fix for nested tags in linkify-html

v2.0.0-beta.7

---

docs/linkify-string.md

Added example of using "linkify-string" for HTML string and an example of how it escapes HTML entities

Add example

---

docs/options.md

Includes changes to github-style code blocks in options.md page
See #125

Docs for new "ignoreTags" option

---

.babelrc
element.js
foo.js
gulpfile.js
html.js
jquery.js
package.json
plugins/hashtag.js
src/linkify-element.js
src/linkify-jquery.js
src/linkify-string.js
src/linkify/plugins/hashtag.js
string.js
tasks/rollup.js
templates/linkify-element.js
templates/linkify-html.js
templates/linkify-jquery.js
templates/linkify-string.js
templates/linkify.js
templates/linkify/plugins/hashtag.js
test/spec/linkify-element-test.js
test/spec/linkify-html-test.js
test/spec/linkify-jquery-test.js
test/spec/linkify-string-test.js
test/spec/linkify/plugins/hashtag-test.js

Build upgrades

---

docs/index.md
docs/linkify-element.md
docs/linkify-html.md
docs/linkify-jquery.md
docs/linkify-string.md
docs/linkify.md
docs/plugins.md
js/main.coffee

Docs updates

---

src/linkify-element.js

Fixing element interface invalid DOM node error

---

src/linkify-element.js
src/linkify-string.js
test/spec/linkify-element-test.js
test/spec/linkify-jquery-test.js

And some more, smaller tweaks
Fixes #145

Linkify element fixes

---

plugins/ticket.js
src/linkify/core/state.js
src/linkify/plugins/hashtag.js
src/linkify/plugins/mention.js
src/linkify/plugins/ticket.js
tasks/uglify.js
templates/linkify/plugins/ticket.amd.js
templates/linkify/plugins/ticket.js
test/amd.conf.js
test/conf.js
test/qunit/main.js
test/spec/linkify/core/state/token-test.js
test/spec/linkify/plugins/hashtag-test.js
test/spec/linkify/plugins/ticket-test.js

Similar to hashtags, but used for github-style issue mentions.

Tickets plugin

---

_layouts/doc.html
docs/linkify.md
docs/options.md
docs/plugin-mention.md

As per #111 - added page links to documentation and page similar to hashtag plugin

Add @mentions documentation

---

src/linkify/core/scanner.js
src/linkify/utils/options.js
test/spec/linkify/core/parser-test.js
test/spec/linkify/core/scanner-test.js

Including non-breaking space. 
Fixes #162

Detect  additional whitespace characters

---

.travis.yml
README.md
package.json
run-tests.sh

* karma-chrome-launcher
* rollup
* simple-html-tokenizer

Small dependency updates

---

package.json
src/linkify-html.js
src/linkify/core/parser.js
src/linkify/core/scanner.js
src/linkify/core/tokens/text.js
test/spec/linkify-html-test.js
test/spec/linkify/core/scanner-test.js

URL followed by &nbsp; now works as expected in linkify-html

---

src/linkify/plugins/mention.js
test/spec/linkify/plugins/mention-test.js

Add support for mentions containing dots

---

src/linkify-react.js

Use class instead of React.createClass

---

src/linkify/core/scanner.js
test/spec/linkify/core/parser-test.js

- Fixes https://github.com/SoapBox/linkifyjs/issues/208

Add partialProtocolMailtoStates to domainStates

---

docs/linkify-react.md

Addresses https://github.com/SoapBox/linkifyjs/issues/248

Update React Event Handler Docs To Be More Helpful

---

src/linkify/core/parser.js
test/spec/linkify/core/parser-test.js

Fixes issue: #279 : emailaddress domains that start with numbers.

Domains starting with numbers fix

---

package.json
packages/linkifyjs/package.json

fix for https://github.com/Hypercontext/linkifyjs/issues/361

support for ES module resolve

---

package-lock.json
package.json
packages/linkifyjs/src/multi.js
test/spec/linkifyjs/options.test.js

Ensure function options get called with unformatted href

---

packages/linkifyjs/src/linkify.js
packages/linkifyjs/src/options.js
test/spec/linkify-jquery.test.js
test/spec/linkifyjs.test.js

Ensure linkify.find() respects validate option

---

package-lock.json
package.json
packages/linkify-html/package.json

To include changes from nfrasser/simple-html-tokenizer#1

Bump simple-html-tokenizer
